!!python/object:argparse.Namespace
act: relu
bs: 16
config: null
device: cuda:0
entity: harrylts
epochs: 125
eval: false
hsize: 492
k1: 1.0
k2: 1.0
k3: 1.0
logdir: models/reno_full/whitebox
lr: 0.0022678287177042957
model_state_dict: null
nlayers: 3
no_wandb: false
nsim: 150
nsteps: 3500
only_summary: true
patience: 40
plot_idx: 0
project: tronn_benchmarks
ref_forecast: 3
remove_savedir: true
save_traces: false
seed: 0
system: Reno_full
test_dir: test_data/control
test_idx: null
test_n: 100
test_nsim: 1
test_nsteps: 3500
time_stamp: true
trace_dir: traces/whitebox
train_prob: 0.0005
