!!python/object:argparse.Namespace
bs: 16
device: cuda:0
entity: harrylts
epochs: 150
eval: false
k1: 1.0
k2: 1.0
k3: 1.0
logdir: models/reno_full/blackbox
lr: 0.0015681759700251314
max_u: 0.0
no_wandb: false
nsim: 200
nsteps: 3500
only_summary: true
optimizer: adam
patience: 40
plot_idx: 0
policy_act: selu
policy_config: null
policy_hsize: 346
policy_model_state_dict: null
policy_nlayers: 1
project: tronn_benchmarks
ref_forecast: 3
remove_savedir: true
save_traces: false
seed: 0
ssm_act: relu
ssm_architecture: LSTM
ssm_config: models/reno_full/blackbox_lstm/config.yaml
ssm_hsize: 364
ssm_model_state_dict: models/reno_full/blackbox_lstm/best_model_state_dict.pth
ssm_nlayers: 3
system: Reno_full
test_dir: test_data/control
test_idx: null
test_n: 100
test_nsim: 1
test_nsteps: 3500
time_stamp: true
trace_dir: traces/blackbox
train_prob: 0.0005
