!!python/object:argparse.Namespace
bs: 256
device: cuda:0
entity: harrylts
epochs: 150
eval: false
k1: 1.0
k2: 1.0
k3: 1.0
logdir: models/simple_single_zone/blackbox
lr: 0.007486321678547709
max_u: 0.0
no_wandb: false
nsim: 50
nsteps: 3500
only_summary: true
patience: 40
plot_idx: 0
policy_act: relu
policy_config: null
policy_hsize: 256
policy_model_state_dict: null
policy_nlayers: 2
project: tronn_benchmarks
ref_forecast: 3
remove_savedir: true
seed: 0
ssm_act: relu
ssm_architecture: MLP_integrator
ssm_config: models/simple_single_zone/legacy_blackbox_ssm/config.yaml
ssm_hsize: 128
ssm_model_state_dict: models/simple_single_zone/legacy_blackbox_ssm/best_model_state_dict.pth
ssm_nlayers: 2
system: SimpleSingleZone
test_dir: test_data/control
test_idx: null
test_n: 100
test_nsim: 1
test_nsteps: 3500
time_stamp: true
train_prob: 0.0005
